# Generated by Django 2.2.12 on 2022-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220630_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avis',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=30),
        ),
    ]
